name: Check CIs
on:
  push:
  schedule:
    - cron: '0 2 * * *'
jobs:
  run:
    strategy:
      fail-fast: false
      matrix:
        type: [release, head]
    name: Check CIs for TruffleRuby ${{ matrix.type }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true

    - run: bin/gem_tracker statuses --ruby=release --days=60
      env:
        GEM_TRACKER_GITHUB_AUTH: ${{ secrets.GEM_TRACKER_GITHUB_AUTH }}
      if: matrix.type == 'release'

    - run: bin/gem_tracker statuses --ruby=head --days=30
      env:
        GEM_TRACKER_GITHUB_AUTH: ${{ secrets.GEM_TRACKER_GITHUB_AUTH }}
      if: matrix.type == 'head'
